### ISSUE TITLE
Jupyter notebook samples

### ISSUE THREAD

**Issue by semeniak1997** [TheAdamProject/UniversalNeuralCrackingMachines#1]
Hello! Thank you for your project.

I'm trying to run your examples from jupyter notebook, doing everything as it says in the description of the project. I downloaded the trained models from links. Tell me how to run or how to correctly specify the path to these trained models. The following warning pops up when I try to run your code:

`WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.`

How to run correctly? Thanks

**Comment by pasquini-dario** [comment]
Hello,

Is the notebook failing during execution, or is it simply that warning? 
If the only issue is the warning, everything should be working properly (that warning is due to how we trained/exported the keras model and should not impact the model's performance).
